<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Promise_B</title>
</head>
<body>
  <script>
    // 期约的实例方法

    // 期约实例的方法是连接外部同步代码与内部异步代码之间的桥梁。这些方法可以访问异步操作返回的数据，
    // 处理期约成功和失败的结果，连续对期约求值，或者添加只有期约进入终止状态时才会执行的代码。

    // 1. 实现 Thenable 接口
    // 在 ECMAScript 暴露的异步结构中，任何对象都有一个 then()方法。这个方法被认为实现了
    // Thenable 接口。下面的例子展示了实现这一接口的最简单的类：
    class MyThenable { 
      then() {} 
    } 
    // ECMAScript 的 Promise 类型实现了 Thenable 接口。这个简化的接口跟 TypeScript 或其他包中的
    // 接口或类型定义不同，它们都设定了 Thenable 接口更具体的形式。

    // 2. Promise.prototype.then()
    // Promise.prototype.then() 是为期约实例添加处理程序的主要方法。这个 then() 方法
    // 接收最多两个参数：onResolved 处理程序和 onRejected 处理程序。这两个参数都是可选的，
    // 如果提供的话，则会在期约分别进入“兑现”和“拒绝”状态时执行。
    function onResolved(id) { setTimeout(console.log, 0, id, 'resolved') } 
    function onRejected(id) { setTimeout(console.log, 0, id, 'rejected') }
    let p1 = new Promise((resolve, reject) => setTimeout(resolve, 3000)); 
    let p2 = new Promise((resolve, reject) => setTimeout(reject, 3000)); 
    p1.then(() => onResolved('p1'), () => onRejected('p1')); 
    p2.then(() => onResolved('p2'), () => onRejected('p2'));
    //（3 秒后）
    // p1 resolved 
    // p2 rejected

    // 因为期约只能转换为最终状态一次，所以两个操作一定是互斥的。
    // 两个处理程序参数都是可选的。而且，传给 then() 的任何非函数类型的参数都会被静默忽略。
    // 如果想只提供 onRejected 参数，那就要在 onResolved 参数的位置上传入 undefined 或 null。
    // 这样有助于避免在内存中创建多余的对象，对期待函数参数的类型系统也是一个交代。
    p1.then('gobbeltygook');               // 无输出       // 非函数处理程序会被静默忽略，不推荐
    p2.then(null, () => onRejected('p2')); // p2 rejected  // 不传 onResolved 处理程序的规范写法

    // Promise.prototype.then() 方法返回一个新的期约实例。
    let p3 = new Promise(() => {}); 
    let p4 = p3.then(); 
    setTimeout(console.log, 0, p3);        // Promise {<pending>}
    setTimeout(console.log, 0, p4);        // Promise {<pending>}
    setTimeout(console.log, 0, p3 === p4); // false

    // 2.1
    // 下面这个返回的新的期约实例是基于 onResovled 处理程序的返回值构建。
    // 换句话说，该处理程序的返回值会通过 Promise.resolve() 包装来生成新期约。
    // 如果没有提供这个处理程序，则 Promise.resolve() 就会包装上一个期约解决之后的值。
    // 如果没有显式的返回语句，则 Promise.resolve() 会包装默认的返回值 undefined。
    let pp1 = Promise.resolve('foo');
    let pp2 = pp1.then();
    setTimeout(console.log, 0, pp2); // Promise {<fulfilled>: 'foo'}
    
    let pp3 = pp1.then(() => undefined);
    let pp4 = pp1.then(() => {}); 
    let pp5 = pp1.then(() => Promise.resolve()); 
    setTimeout(console.log, 0, pp3); // Promise {<fulfilled>: undefined}
    setTimeout(console.log, 0, pp4); // Promise {<fulfilled>: undefined}
    setTimeout(console.log, 0, pp5); // Promise {<fulfilled>: undefined}

    // 如果有显式的返回值，则 Promise.resolve() 会包装这个值
    let pppp6 = pp1.then(() => 'bar'); 
    let pppp7 = pp1.then(() => Promise.resolve('bar')); 
    setTimeout(console.log, 0, pppp6); // Promise {<fulfilled>: 'bar'}
    setTimeout(console.log, 0, pppp7); // Promise {<fulfilled>: 'bar'}

    // Promise.resolve() 保留返回的期约
    let pppp8 = pp1.then(() => new Promise(() => {})); 
    let pppp9 = pp1.then(() => Promise.reject()); 
    // Uncaught (in promise): undefined 
    setTimeout(console.log, 0, pppp8); // Promise {<pending>}
    setTimeout(console.log, 0, pppp9); // Promise {<rejected>: undefined}
    
    // 抛出异常会返回拒绝的期约：
    let pppp10 = pp1.then(() => { throw 'baz'; }); 
    // Uncaught (in promise) baz 
    setTimeout(console.log, 0, pppp10); // Promise {<rejected>: 'baz'}
    
    // 返回错误值不会触发上面的拒绝行为，而会把错误对象包装在一个解决的期约中
    let pppp11 = pp1.then(() => Error('qux')); 
    setTimeout(console.log, 0, pppp11); // Promise {<fulfilled>: Error: qux}

    // 2.2
    // onRejected 处理程序也与之类似：onRejected 处理程序返回的值也会被 Promise.resolve() 包装。
    // 乍一看这可能有点违反直觉，但是想一想，onRejected 处理程序的任务不就是捕获异步错误吗？
    // 因此，拒绝处理程序在捕获错误后不抛出异常是符合期约的行为，应该返回一个解决期约。

    let ppp1 = Promise.reject('foo'); // 调用 then() 时不传处理程序则原样向后传
    // Uncaught (in promise) foo
    let ppp2 = ppp1.then(); 
    setTimeout(console.log, 0, ppp2); // Promise {<rejected>: 'foo'}

    let ppp3 = ppp1.then(null, () => undefined); 
    let ppp4 = ppp1.then(null, () => {}); 
    let ppp5 = ppp1.then(null, () => Promise.resolve()); 
    setTimeout(console.log, 0, ppp3); // Promise {<fulfilled>: undefined} 
    setTimeout(console.log, 0, ppp4); // Promise {<fulfilled>: undefined} 
    setTimeout(console.log, 0, ppp5); // Promise {<fulfilled>: undefined}

    let ppp6 = ppp1.then(null, () => 'bar'); 
    let ppp7 = ppp1.then(null, () => Promise.resolve('bar')); 
    setTimeout(console.log, 0, ppp6); // Promise {<fulfilled>: 'bar'}
    setTimeout(console.log, 0, ppp7); // Promise {<fulfilled>: 'bar'}

    // Promise.resolve() 保留返回的期约
    let ppp8 = ppp1.then(null, () => new Promise(() => {})); 
    let ppp9 = ppp1.then(null, () => Promise.reject()); 
    // Uncaught (in promise): undefined 
    setTimeout(console.log, 0, ppp8); // Promise {<pending>}
    setTimeout(console.log, 0, ppp9); // Promise {<rejected>: undefined}

    let ppp10 = ppp1.then(null, () => { throw 'baz'; }); 
    // Uncaught (in promise) baz 
    setTimeout(console.log, 0, ppp10); // Promise {<rejected>: 'baz'}
    
    let ppp11 = ppp1.then(null, () => Error('qux')); 
    setTimeout(console.log, 0, ppp11); // Promise {<fulfilled>: Error: qux}

    // 3. Promise.prototype.catch()
    // Promise.prototype.catch() 方法用于给期约添加拒绝处理程序。
    // 这个方法只接收一个参数：onRejected 处理程序。事实上，这个方法就是一个语法糖，
    // 调用它就相当于调用 Promise.prototype.then(null, onRejected)。
    let p = Promise.reject(); 
    // Uncaught (in promise) undefined
    let catchRejected = function(e) { 
    setTimeout(console.log, 0, 'rejected'); 
    }; 
    // 这两种添加拒绝处理程序的方式是一样的：
    p.then(null, catchRejected); // rejected 
    p.catch(catchRejected);      // rejected

    // Promise.prototype.catch() 返回一个新的期约实例。在返回新期约实例方面，
    // Promise.prototype.catch() 的行为与 Promise.prototype.then() 的 onRejected 处理程序是一样的。
    let catchp1 = new Promise(() => {}); 
    let catchp2 = catchp1.catch(); 
    setTimeout(console.log, 0, catchp1); // Promise {<pending>}
    setTimeout(console.log, 0, catchp2); // Promise {<pending>}
    setTimeout(console.log, 0, catchp1 === catchp2); // false

    // 4. Promise.prototype.finally()
    // Promise.prototype.finally() 方法用于给期约添加 onFinally 处理程序，这个处理程序在期约转换为
    // 解决或拒绝状态时都会执行。这个方法可以避免 onResolved 和 onRejected 处理程序中出现冗余代码。
    // 但 onFinally 处理程序没有办法知道期约的状态是解决还是拒绝，所以这个方法主要用于添加清理代码。
    let finallyp1 = Promise.resolve(); 
    let finallyp2 = Promise.reject(); 
    let onFinally = function() { 
    setTimeout(console.log, 0, 'Finally!') 
    } 
    finallyp1.finally(onFinally); // Finally!
    finallyp2.finally(onFinally); // Finally!

    // Promise.prototype.finally() 方法返回一个新的期约实例
    let finallypp1 = new Promise(() => {}); 
    let finallypp2 = finallypp1.finally();
    setTimeout(console.log, 0, finallypp1);                // Promise {<pending>}
    setTimeout(console.log, 0, finallypp2);                // Promise {<pending>}
    setTimeout(console.log, 0, finallypp1 === finallypp2); // false

    // 这个新期约实例不同于 then() 或 catch() 方式返回的实例。因为 onFinally 被设计为一个状态
    // 无关的方法，所以在大多数情况下它将表现为父期约的传递。对于已解决状态和被拒绝状态都是如此。

    let finallyppp1 = Promise.resolve('foo'); 
    // 这里都会原样后传
    let finallyppp2 = finallyppp1.finally(); 
    let finallyppp3 = finallyppp1.finally(() => undefined); 
    let finallyppp4 = finallyppp1.finally(() => {}); 
    let finallyppp5 = finallyppp1.finally(() => Promise.resolve()); 
    let finallyppp6 = finallyppp1.finally(() => 'bar'); 
    let finallyppp7 = finallyppp1.finally(() => Promise.resolve('bar')); 
    let finallyppp8 = finallyppp1.finally(() => Error('qux')); 
    setTimeout(console.log, 0, finallyppp2); // Promise {<fulfilled>: 'foo'}
    setTimeout(console.log, 0, finallyppp3); // Promise {<fulfilled>: 'foo'}
    setTimeout(console.log, 0, finallyppp4); // Promise {<fulfilled>: 'foo'}
    setTimeout(console.log, 0, finallyppp5); // Promise {<fulfilled>: 'foo'}
    setTimeout(console.log, 0, finallyppp6); // Promise {<fulfilled>: 'foo'}
    setTimeout(console.log, 0, finallyppp7); // Promise {<fulfilled>: 'foo'}
    setTimeout(console.log, 0, finallyppp8); // Promise {<fulfilled>: 'foo'}

    // 如果返回的是一个待定的期约，或者 onFinally 处理程序抛出了错误（显式抛出或返回了
    // 一个拒绝期约），则会返回相应的期约（待定或拒绝）。

    // Promise.resolve() 保留返回的期约
    let finallyppp9 = finallyppp1.finally(() => new Promise(() => {})); 
    let finallyppp10 = finallyppp1.finally(() => Promise.reject()); 
    // Uncaught (in promise): undefined 
    setTimeout(console.log, 0, finallyppp9);  // Promise {<pending>}
    setTimeout(console.log, 0, finallyppp10); // Promise {<rejected>: undefined}

    let finallyppp11 = finallyppp1.finally(() => { throw 'baz'; }); 
    // Uncaught (in promise) baz 
    setTimeout(console.log, 0, finallyppp11); // Promise {<rejected>: 'baz'}

    // 返回待定期约的情形并不常见，这是因为只要期约一解决，新期约仍然会原样后传初始的期约：
    let finallypppp1 = Promise.resolve('foo'); 
    // 忽略解决的值
    let finallypppp2 = finallypppp1.finally( 
    () => new Promise((resolve, reject) => setTimeout(() => resolve('bar'), 100))); 
    
    setTimeout(console.log, 0, finallypppp2); // Promise {<pending>}
    setTimeout(() => setTimeout(console.log, 0, finallypppp2), 200); 
    // 200 毫秒后：// Promise {<fulfilled>: 'foo'}
  </script>
</body>
</html>